package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_binary(
    name = "beam_sample_tfrecord",
    srcs = [
        "beam_sample_tfrecord.py",
    ],
    deps = ["//tf_util:example_util"],
)

py_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
)
