package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "transit_fns",
    srcs = [
        "transit_fns.py",
    ],
    deps = [
        "//experimental/light_curve_util:transit_model",
        "//light_curve:periodic_event",
        "//light_curve:util",
    ],
)
